/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.contact.service.model.impl;

import com.dogoo.contact.service.model.ContactEntry;
import com.dogoo.contact.service.model.ContactEntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ContactEntry service. Represents a row in the &quot;DG_ContactEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ContactEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactEntryImpl
 * @generated
 */
public class ContactEntryModelImpl
	extends BaseModelImpl<ContactEntry> implements ContactEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contact entry model instance should use the <code>ContactEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DG_ContactEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"contactId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"creatorId", Types.BIGINT},
		{"customerId", Types.BIGINT}, {"facebook", Types.VARCHAR},
		{"twitter", Types.VARCHAR}, {"linkedin", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("creatorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("customerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("facebook", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("twitter", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("linkedin", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DG_ContactEntry (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,contactId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,creatorId LONG,customerId LONG,facebook VARCHAR(75) null,twitter VARCHAR(75) null,linkedin VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table DG_ContactEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY contactEntry.facebook ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DG_ContactEntry.facebook ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACEBOOK_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ContactEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contactId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContactId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contactId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ContactEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ContactEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ContactEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ContactEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ContactEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ContactEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ContactEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ContactEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ContactEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ContactEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ContactEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ContactEntry.class.getClassLoader(), ContactEntry.class,
			ModelWrapper.class);

		try {
			Constructor<ContactEntry> constructor =
				(Constructor<ContactEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ContactEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ContactEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ContactEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ContactEntry, Object>>();
		Map<String, BiConsumer<ContactEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ContactEntry, ?>>();

		attributeGetterFunctions.put("uuid", ContactEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<ContactEntry, String>)ContactEntry::setUuid);
		attributeGetterFunctions.put(
			"externalReferenceCode", ContactEntry::getExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<ContactEntry, String>)
				ContactEntry::setExternalReferenceCode);
		attributeGetterFunctions.put("contactId", ContactEntry::getContactId);
		attributeSetterBiConsumers.put(
			"contactId",
			(BiConsumer<ContactEntry, Long>)ContactEntry::setContactId);
		attributeGetterFunctions.put("groupId", ContactEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ContactEntry, Long>)ContactEntry::setGroupId);
		attributeGetterFunctions.put("companyId", ContactEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ContactEntry, Long>)ContactEntry::setCompanyId);
		attributeGetterFunctions.put("userId", ContactEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<ContactEntry, Long>)ContactEntry::setUserId);
		attributeGetterFunctions.put("userName", ContactEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<ContactEntry, String>)ContactEntry::setUserName);
		attributeGetterFunctions.put("createDate", ContactEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ContactEntry, Date>)ContactEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", ContactEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ContactEntry, Date>)ContactEntry::setModifiedDate);
		attributeGetterFunctions.put("creatorId", ContactEntry::getCreatorId);
		attributeSetterBiConsumers.put(
			"creatorId",
			(BiConsumer<ContactEntry, Long>)ContactEntry::setCreatorId);
		attributeGetterFunctions.put("customerId", ContactEntry::getCustomerId);
		attributeSetterBiConsumers.put(
			"customerId",
			(BiConsumer<ContactEntry, Long>)ContactEntry::setCustomerId);
		attributeGetterFunctions.put("facebook", ContactEntry::getFacebook);
		attributeSetterBiConsumers.put(
			"facebook",
			(BiConsumer<ContactEntry, String>)ContactEntry::setFacebook);
		attributeGetterFunctions.put("twitter", ContactEntry::getTwitter);
		attributeSetterBiConsumers.put(
			"twitter",
			(BiConsumer<ContactEntry, String>)ContactEntry::setTwitter);
		attributeGetterFunctions.put("linkedin", ContactEntry::getLinkedin);
		attributeSetterBiConsumers.put(
			"linkedin",
			(BiConsumer<ContactEntry, String>)ContactEntry::setLinkedin);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@Override
	public long getContactId() {
		return _contactId;
	}

	@Override
	public void setContactId(long contactId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactId = contactId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCreatorId() {
		return _creatorId;
	}

	@Override
	public void setCreatorId(long creatorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creatorId = creatorId;
	}

	@Override
	public long getCustomerId() {
		return _customerId;
	}

	@Override
	public void setCustomerId(long customerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customerId = customerId;
	}

	@Override
	public String getFacebook() {
		if (_facebook == null) {
			return "";
		}
		else {
			return _facebook;
		}
	}

	@Override
	public void setFacebook(String facebook) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facebook = facebook;
	}

	@Override
	public String getTwitter() {
		if (_twitter == null) {
			return "";
		}
		else {
			return _twitter;
		}
	}

	@Override
	public void setTwitter(String twitter) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_twitter = twitter;
	}

	@Override
	public String getLinkedin() {
		if (_linkedin == null) {
			return "";
		}
		else {
			return _linkedin;
		}
	}

	@Override
	public void setLinkedin(String linkedin) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_linkedin = linkedin;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(ContactEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ContactEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContactEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ContactEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContactEntryImpl contactEntryImpl = new ContactEntryImpl();

		contactEntryImpl.setUuid(getUuid());
		contactEntryImpl.setExternalReferenceCode(getExternalReferenceCode());
		contactEntryImpl.setContactId(getContactId());
		contactEntryImpl.setGroupId(getGroupId());
		contactEntryImpl.setCompanyId(getCompanyId());
		contactEntryImpl.setUserId(getUserId());
		contactEntryImpl.setUserName(getUserName());
		contactEntryImpl.setCreateDate(getCreateDate());
		contactEntryImpl.setModifiedDate(getModifiedDate());
		contactEntryImpl.setCreatorId(getCreatorId());
		contactEntryImpl.setCustomerId(getCustomerId());
		contactEntryImpl.setFacebook(getFacebook());
		contactEntryImpl.setTwitter(getTwitter());
		contactEntryImpl.setLinkedin(getLinkedin());

		contactEntryImpl.resetOriginalValues();

		return contactEntryImpl;
	}

	@Override
	public ContactEntry cloneWithOriginalValues() {
		ContactEntryImpl contactEntryImpl = new ContactEntryImpl();

		contactEntryImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		contactEntryImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		contactEntryImpl.setContactId(
			this.<Long>getColumnOriginalValue("contactId"));
		contactEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		contactEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		contactEntryImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		contactEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		contactEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		contactEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		contactEntryImpl.setCreatorId(
			this.<Long>getColumnOriginalValue("creatorId"));
		contactEntryImpl.setCustomerId(
			this.<Long>getColumnOriginalValue("customerId"));
		contactEntryImpl.setFacebook(
			this.<String>getColumnOriginalValue("facebook"));
		contactEntryImpl.setTwitter(
			this.<String>getColumnOriginalValue("twitter"));
		contactEntryImpl.setLinkedin(
			this.<String>getColumnOriginalValue("linkedin"));

		return contactEntryImpl;
	}

	@Override
	public int compareTo(ContactEntry contactEntry) {
		int value = 0;

		value = getFacebook().compareTo(contactEntry.getFacebook());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ContactEntry)) {
			return false;
		}

		ContactEntry contactEntry = (ContactEntry)object;

		long primaryKey = contactEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ContactEntry> toCacheModel() {
		ContactEntryCacheModel contactEntryCacheModel =
			new ContactEntryCacheModel();

		contactEntryCacheModel.uuid = getUuid();

		String uuid = contactEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			contactEntryCacheModel.uuid = null;
		}

		contactEntryCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			contactEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			contactEntryCacheModel.externalReferenceCode = null;
		}

		contactEntryCacheModel.contactId = getContactId();

		contactEntryCacheModel.groupId = getGroupId();

		contactEntryCacheModel.companyId = getCompanyId();

		contactEntryCacheModel.userId = getUserId();

		contactEntryCacheModel.userName = getUserName();

		String userName = contactEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			contactEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			contactEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			contactEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			contactEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			contactEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		contactEntryCacheModel.creatorId = getCreatorId();

		contactEntryCacheModel.customerId = getCustomerId();

		contactEntryCacheModel.facebook = getFacebook();

		String facebook = contactEntryCacheModel.facebook;

		if ((facebook != null) && (facebook.length() == 0)) {
			contactEntryCacheModel.facebook = null;
		}

		contactEntryCacheModel.twitter = getTwitter();

		String twitter = contactEntryCacheModel.twitter;

		if ((twitter != null) && (twitter.length() == 0)) {
			contactEntryCacheModel.twitter = null;
		}

		contactEntryCacheModel.linkedin = getLinkedin();

		String linkedin = contactEntryCacheModel.linkedin;

		if ((linkedin != null) && (linkedin.length() == 0)) {
			contactEntryCacheModel.linkedin = null;
		}

		return contactEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ContactEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ContactEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ContactEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ContactEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ContactEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ContactEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ContactEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _externalReferenceCode;
	private long _contactId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _creatorId;
	private long _customerId;
	private String _facebook;
	private String _twitter;
	private String _linkedin;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ContactEntry, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ContactEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("contactId", _contactId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("creatorId", _creatorId);
		_columnOriginalValues.put("customerId", _customerId);
		_columnOriginalValues.put("facebook", _facebook);
		_columnOriginalValues.put("twitter", _twitter);
		_columnOriginalValues.put("linkedin", _linkedin);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("contactId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("creatorId", 512L);

		columnBitmasks.put("customerId", 1024L);

		columnBitmasks.put("facebook", 2048L);

		columnBitmasks.put("twitter", 4096L);

		columnBitmasks.put("linkedin", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ContactEntry _escapedModel;

}