/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.contact.service.model.impl;

import com.dogoo.contact.service.model.PhoneEntry;
import com.dogoo.contact.service.model.PhoneEntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PhoneEntry service. Represents a row in the &quot;DG_PhoneEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PhoneEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhoneEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhoneEntryImpl
 * @generated
 */
public class PhoneEntryModelImpl
	extends BaseModelImpl<PhoneEntry> implements PhoneEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phone entry model instance should use the <code>PhoneEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DG_PhoneEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"phoneId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"creatorId", Types.BIGINT},
		{"customerId", Types.BIGINT}, {"contactId", Types.BIGINT},
		{"number_", Types.VARCHAR}, {"isDefaulted", Types.BOOLEAN},
		{"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phoneId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("creatorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("customerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("number_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isDefaulted", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DG_PhoneEntry (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,phoneId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,creatorId LONG,customerId LONG,contactId LONG,number_ VARCHAR(75) null,isDefaulted BOOLEAN,description VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table DG_PhoneEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY phoneEntry.phoneId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DG_PhoneEntry.phoneId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONTACTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CUSTOMERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISDEFAULTED_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NUMBER_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PHONEID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PhoneEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _phoneId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPhoneId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _phoneId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PhoneEntry.class;
	}

	@Override
	public String getModelClassName() {
		return PhoneEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PhoneEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PhoneEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhoneEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((PhoneEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PhoneEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PhoneEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PhoneEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PhoneEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PhoneEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PhoneEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PhoneEntry.class.getClassLoader(), PhoneEntry.class,
			ModelWrapper.class);

		try {
			Constructor<PhoneEntry> constructor =
				(Constructor<PhoneEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PhoneEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PhoneEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PhoneEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PhoneEntry, Object>>();
		Map<String, BiConsumer<PhoneEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PhoneEntry, ?>>();

		attributeGetterFunctions.put("uuid", PhoneEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<PhoneEntry, String>)PhoneEntry::setUuid);
		attributeGetterFunctions.put(
			"externalReferenceCode", PhoneEntry::getExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<PhoneEntry, String>)
				PhoneEntry::setExternalReferenceCode);
		attributeGetterFunctions.put("phoneId", PhoneEntry::getPhoneId);
		attributeSetterBiConsumers.put(
			"phoneId", (BiConsumer<PhoneEntry, Long>)PhoneEntry::setPhoneId);
		attributeGetterFunctions.put("groupId", PhoneEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<PhoneEntry, Long>)PhoneEntry::setGroupId);
		attributeGetterFunctions.put("companyId", PhoneEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<PhoneEntry, Long>)PhoneEntry::setCompanyId);
		attributeGetterFunctions.put("userId", PhoneEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<PhoneEntry, Long>)PhoneEntry::setUserId);
		attributeGetterFunctions.put("userName", PhoneEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<PhoneEntry, String>)PhoneEntry::setUserName);
		attributeGetterFunctions.put("createDate", PhoneEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<PhoneEntry, Date>)PhoneEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", PhoneEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<PhoneEntry, Date>)PhoneEntry::setModifiedDate);
		attributeGetterFunctions.put("creatorId", PhoneEntry::getCreatorId);
		attributeSetterBiConsumers.put(
			"creatorId",
			(BiConsumer<PhoneEntry, Long>)PhoneEntry::setCreatorId);
		attributeGetterFunctions.put("customerId", PhoneEntry::getCustomerId);
		attributeSetterBiConsumers.put(
			"customerId",
			(BiConsumer<PhoneEntry, Long>)PhoneEntry::setCustomerId);
		attributeGetterFunctions.put("contactId", PhoneEntry::getContactId);
		attributeSetterBiConsumers.put(
			"contactId",
			(BiConsumer<PhoneEntry, Long>)PhoneEntry::setContactId);
		attributeGetterFunctions.put("number", PhoneEntry::getNumber);
		attributeSetterBiConsumers.put(
			"number", (BiConsumer<PhoneEntry, String>)PhoneEntry::setNumber);
		attributeGetterFunctions.put("isDefaulted", PhoneEntry::getIsDefaulted);
		attributeSetterBiConsumers.put(
			"isDefaulted",
			(BiConsumer<PhoneEntry, Boolean>)PhoneEntry::setIsDefaulted);
		attributeGetterFunctions.put("description", PhoneEntry::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<PhoneEntry, String>)PhoneEntry::setDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@Override
	public long getPhoneId() {
		return _phoneId;
	}

	@Override
	public void setPhoneId(long phoneId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phoneId = phoneId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCreatorId() {
		return _creatorId;
	}

	@Override
	public void setCreatorId(long creatorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creatorId = creatorId;
	}

	@Override
	public long getCustomerId() {
		return _customerId;
	}

	@Override
	public void setCustomerId(long customerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customerId = customerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCustomerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("customerId"));
	}

	@Override
	public long getContactId() {
		return _contactId;
	}

	@Override
	public void setContactId(long contactId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactId = contactId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalContactId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("contactId"));
	}

	@Override
	public String getNumber() {
		if (_number == null) {
			return "";
		}
		else {
			return _number;
		}
	}

	@Override
	public void setNumber(String number) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_number = number;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNumber() {
		return getColumnOriginalValue("number_");
	}

	@Override
	public boolean getIsDefaulted() {
		return _isDefaulted;
	}

	@Override
	public boolean isIsDefaulted() {
		return _isDefaulted;
	}

	@Override
	public void setIsDefaulted(boolean isDefaulted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isDefaulted = isDefaulted;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsDefaulted() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isDefaulted"));
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(PhoneEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PhoneEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PhoneEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PhoneEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PhoneEntryImpl phoneEntryImpl = new PhoneEntryImpl();

		phoneEntryImpl.setUuid(getUuid());
		phoneEntryImpl.setExternalReferenceCode(getExternalReferenceCode());
		phoneEntryImpl.setPhoneId(getPhoneId());
		phoneEntryImpl.setGroupId(getGroupId());
		phoneEntryImpl.setCompanyId(getCompanyId());
		phoneEntryImpl.setUserId(getUserId());
		phoneEntryImpl.setUserName(getUserName());
		phoneEntryImpl.setCreateDate(getCreateDate());
		phoneEntryImpl.setModifiedDate(getModifiedDate());
		phoneEntryImpl.setCreatorId(getCreatorId());
		phoneEntryImpl.setCustomerId(getCustomerId());
		phoneEntryImpl.setContactId(getContactId());
		phoneEntryImpl.setNumber(getNumber());
		phoneEntryImpl.setIsDefaulted(isIsDefaulted());
		phoneEntryImpl.setDescription(getDescription());

		phoneEntryImpl.resetOriginalValues();

		return phoneEntryImpl;
	}

	@Override
	public PhoneEntry cloneWithOriginalValues() {
		PhoneEntryImpl phoneEntryImpl = new PhoneEntryImpl();

		phoneEntryImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		phoneEntryImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		phoneEntryImpl.setPhoneId(this.<Long>getColumnOriginalValue("phoneId"));
		phoneEntryImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		phoneEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		phoneEntryImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		phoneEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		phoneEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		phoneEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		phoneEntryImpl.setCreatorId(
			this.<Long>getColumnOriginalValue("creatorId"));
		phoneEntryImpl.setCustomerId(
			this.<Long>getColumnOriginalValue("customerId"));
		phoneEntryImpl.setContactId(
			this.<Long>getColumnOriginalValue("contactId"));
		phoneEntryImpl.setNumber(
			this.<String>getColumnOriginalValue("number_"));
		phoneEntryImpl.setIsDefaulted(
			this.<Boolean>getColumnOriginalValue("isDefaulted"));
		phoneEntryImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));

		return phoneEntryImpl;
	}

	@Override
	public int compareTo(PhoneEntry phoneEntry) {
		long primaryKey = phoneEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PhoneEntry)) {
			return false;
		}

		PhoneEntry phoneEntry = (PhoneEntry)object;

		long primaryKey = phoneEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PhoneEntry> toCacheModel() {
		PhoneEntryCacheModel phoneEntryCacheModel = new PhoneEntryCacheModel();

		phoneEntryCacheModel.uuid = getUuid();

		String uuid = phoneEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			phoneEntryCacheModel.uuid = null;
		}

		phoneEntryCacheModel.externalReferenceCode = getExternalReferenceCode();

		String externalReferenceCode =
			phoneEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			phoneEntryCacheModel.externalReferenceCode = null;
		}

		phoneEntryCacheModel.phoneId = getPhoneId();

		phoneEntryCacheModel.groupId = getGroupId();

		phoneEntryCacheModel.companyId = getCompanyId();

		phoneEntryCacheModel.userId = getUserId();

		phoneEntryCacheModel.userName = getUserName();

		String userName = phoneEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			phoneEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			phoneEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			phoneEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			phoneEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			phoneEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		phoneEntryCacheModel.creatorId = getCreatorId();

		phoneEntryCacheModel.customerId = getCustomerId();

		phoneEntryCacheModel.contactId = getContactId();

		phoneEntryCacheModel.number = getNumber();

		String number = phoneEntryCacheModel.number;

		if ((number != null) && (number.length() == 0)) {
			phoneEntryCacheModel.number = null;
		}

		phoneEntryCacheModel.isDefaulted = isIsDefaulted();

		phoneEntryCacheModel.description = getDescription();

		String description = phoneEntryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			phoneEntryCacheModel.description = null;
		}

		return phoneEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PhoneEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PhoneEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhoneEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PhoneEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PhoneEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PhoneEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PhoneEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PhoneEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PhoneEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _externalReferenceCode;
	private long _phoneId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _creatorId;
	private long _customerId;
	private long _contactId;
	private String _number;
	private boolean _isDefaulted;
	private String _description;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<PhoneEntry, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PhoneEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("phoneId", _phoneId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("creatorId", _creatorId);
		_columnOriginalValues.put("customerId", _customerId);
		_columnOriginalValues.put("contactId", _contactId);
		_columnOriginalValues.put("number_", _number);
		_columnOriginalValues.put("isDefaulted", _isDefaulted);
		_columnOriginalValues.put("description", _description);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("number_", "number");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("phoneId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("creatorId", 512L);

		columnBitmasks.put("customerId", 1024L);

		columnBitmasks.put("contactId", 2048L);

		columnBitmasks.put("number_", 4096L);

		columnBitmasks.put("isDefaulted", 8192L);

		columnBitmasks.put("description", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PhoneEntry _escapedModel;

}