/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.common.auditing.service.service.base;

import com.dogoo.common.auditing.service.model.AuditingEntry;
import com.dogoo.common.auditing.service.service.AuditingEntryLocalService;
import com.dogoo.common.auditing.service.service.AuditingEntryLocalServiceUtil;
import com.dogoo.common.auditing.service.service.persistence.AuditingEntryPersistence;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the auditing entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dogoo.common.auditing.service.service.impl.AuditingEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dogoo.common.auditing.service.service.impl.AuditingEntryLocalServiceImpl
 * @generated
 */
public abstract class AuditingEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, AuditingEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AuditingEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AuditingEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the auditing entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditingEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditingEntry the auditing entry
	 * @return the auditing entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AuditingEntry addAuditingEntry(AuditingEntry auditingEntry) {
		auditingEntry.setNew(true);

		return auditingEntryPersistence.update(auditingEntry);
	}

	/**
	 * Creates a new auditing entry with the primary key. Does not add the auditing entry to the database.
	 *
	 * @param auditingId the primary key for the new auditing entry
	 * @return the new auditing entry
	 */
	@Override
	@Transactional(enabled = false)
	public AuditingEntry createAuditingEntry(long auditingId) {
		return auditingEntryPersistence.create(auditingId);
	}

	/**
	 * Deletes the auditing entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditingEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditingId the primary key of the auditing entry
	 * @return the auditing entry that was removed
	 * @throws PortalException if a auditing entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AuditingEntry deleteAuditingEntry(long auditingId)
		throws PortalException {

		return auditingEntryPersistence.remove(auditingId);
	}

	/**
	 * Deletes the auditing entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditingEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditingEntry the auditing entry
	 * @return the auditing entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AuditingEntry deleteAuditingEntry(AuditingEntry auditingEntry) {
		return auditingEntryPersistence.remove(auditingEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return auditingEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AuditingEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return auditingEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.common.auditing.service.model.impl.AuditingEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return auditingEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.common.auditing.service.model.impl.AuditingEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return auditingEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return auditingEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return auditingEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AuditingEntry fetchAuditingEntry(long auditingId) {
		return auditingEntryPersistence.fetchByPrimaryKey(auditingId);
	}

	/**
	 * Returns the auditing entry matching the UUID and group.
	 *
	 * @param uuid the auditing entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching auditing entry, or <code>null</code> if a matching auditing entry could not be found
	 */
	@Override
	public AuditingEntry fetchAuditingEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return auditingEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the auditing entry with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the auditing entry's external reference code
	 * @return the matching auditing entry, or <code>null</code> if a matching auditing entry could not be found
	 */
	@Override
	public AuditingEntry fetchAuditingEntryByExternalReferenceCode(
		long companyId, String externalReferenceCode) {

		return auditingEntryPersistence.fetchByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * @deprecated As of Cavanaugh (7.4.x), replaced by {@link #fetchAuditingEntryByExternalReferenceCode(long, String)}
	 */
	@Deprecated
	@Override
	public AuditingEntry fetchAuditingEntryByReferenceCode(
		long companyId, String externalReferenceCode) {

		return fetchAuditingEntryByExternalReferenceCode(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the auditing entry with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the auditing entry's external reference code
	 * @return the matching auditing entry
	 * @throws PortalException if a matching auditing entry could not be found
	 */
	@Override
	public AuditingEntry getAuditingEntryByExternalReferenceCode(
			long companyId, String externalReferenceCode)
		throws PortalException {

		return auditingEntryPersistence.findByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the auditing entry with the primary key.
	 *
	 * @param auditingId the primary key of the auditing entry
	 * @return the auditing entry
	 * @throws PortalException if a auditing entry with the primary key could not be found
	 */
	@Override
	public AuditingEntry getAuditingEntry(long auditingId)
		throws PortalException {

		return auditingEntryPersistence.findByPrimaryKey(auditingId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(auditingEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AuditingEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditingId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			auditingEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AuditingEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("auditingId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(auditingEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AuditingEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("auditingId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return auditingEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return auditingEntryLocalService.deleteAuditingEntry(
			(AuditingEntry)persistedModel);
	}

	@Override
	public BasePersistence<AuditingEntry> getBasePersistence() {
		return auditingEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return auditingEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the auditing entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the auditing entries
	 * @param companyId the primary key of the company
	 * @return the matching auditing entries, or an empty list if no matches were found
	 */
	@Override
	public List<AuditingEntry> getAuditingEntriesByUuidAndCompanyId(
		String uuid, long companyId) {

		return auditingEntryPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of auditing entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the auditing entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of auditing entries
	 * @param end the upper bound of the range of auditing entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching auditing entries, or an empty list if no matches were found
	 */
	@Override
	public List<AuditingEntry> getAuditingEntriesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<AuditingEntry> orderByComparator) {

		return auditingEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the auditing entry matching the UUID and group.
	 *
	 * @param uuid the auditing entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching auditing entry
	 * @throws PortalException if a matching auditing entry could not be found
	 */
	@Override
	public AuditingEntry getAuditingEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return auditingEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the auditing entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.common.auditing.service.model.impl.AuditingEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of auditing entries
	 * @param end the upper bound of the range of auditing entries (not inclusive)
	 * @return the range of auditing entries
	 */
	@Override
	public List<AuditingEntry> getAuditingEntries(int start, int end) {
		return auditingEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of auditing entries.
	 *
	 * @return the number of auditing entries
	 */
	@Override
	public int getAuditingEntriesCount() {
		return auditingEntryPersistence.countAll();
	}

	/**
	 * Updates the auditing entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AuditingEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param auditingEntry the auditing entry
	 * @return the auditing entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AuditingEntry updateAuditingEntry(AuditingEntry auditingEntry) {
		return auditingEntryPersistence.update(auditingEntry);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AuditingEntryLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		auditingEntryLocalService = (AuditingEntryLocalService)aopProxy;

		_setLocalServiceUtilService(auditingEntryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AuditingEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AuditingEntry.class;
	}

	protected String getModelClassName() {
		return AuditingEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = auditingEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AuditingEntryLocalService auditingEntryLocalService) {

		try {
			Field field = AuditingEntryLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, auditingEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected AuditingEntryLocalService auditingEntryLocalService;

	@Reference
	protected AuditingEntryPersistence auditingEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}