/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.common.files.manager.service.model.impl;

import com.dogoo.common.files.manager.service.model.DGFileGeneralPermissionEntry;
import com.dogoo.common.files.manager.service.model.DGFileGeneralPermissionEntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DGFileGeneralPermissionEntry service. Represents a row in the &quot;DG_FileGeneralPermission&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DGFileGeneralPermissionEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DGFileGeneralPermissionEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DGFileGeneralPermissionEntryImpl
 * @generated
 */
public class DGFileGeneralPermissionEntryModelImpl
	extends BaseModelImpl<DGFileGeneralPermissionEntry>
	implements DGFileGeneralPermissionEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dg file general permission entry model instance should use the <code>DGFileGeneralPermissionEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DG_FileGeneralPermission";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"fileGeneralPermissionId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"customerId", Types.BIGINT},
		{"creatorId", Types.BIGINT}, {"fileId", Types.BIGINT},
		{"allowed", Types.VARCHAR}, {"role_", Types.VARCHAR},
		{"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileGeneralPermissionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("customerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("creatorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("allowed", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("role_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DG_FileGeneralPermission (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,fileGeneralPermissionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,customerId LONG,creatorId LONG,fileId LONG,allowed VARCHAR(75) null,role_ VARCHAR(75) null,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table DG_FileGeneralPermission";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dgFileGeneralPermissionEntry.fileGeneralPermissionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DG_FileGeneralPermission.fileGeneralPermissionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CUSTOMERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILEGENERALPERMISSIONID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DGFileGeneralPermissionEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fileGeneralPermissionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFileGeneralPermissionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fileGeneralPermissionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DGFileGeneralPermissionEntry.class;
	}

	@Override
	public String getModelClassName() {
		return DGFileGeneralPermissionEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DGFileGeneralPermissionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DGFileGeneralPermissionEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DGFileGeneralPermissionEntry, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(DGFileGeneralPermissionEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DGFileGeneralPermissionEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DGFileGeneralPermissionEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DGFileGeneralPermissionEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DGFileGeneralPermissionEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DGFileGeneralPermissionEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DGFileGeneralPermissionEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DGFileGeneralPermissionEntry.class.getClassLoader(),
			DGFileGeneralPermissionEntry.class, ModelWrapper.class);

		try {
			Constructor<DGFileGeneralPermissionEntry> constructor =
				(Constructor<DGFileGeneralPermissionEntry>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<DGFileGeneralPermissionEntry, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<DGFileGeneralPermissionEntry, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<DGFileGeneralPermissionEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<DGFileGeneralPermissionEntry, Object>>();
		Map<String, BiConsumer<DGFileGeneralPermissionEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<DGFileGeneralPermissionEntry, ?>>();

		attributeGetterFunctions.put(
			"uuid", DGFileGeneralPermissionEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<DGFileGeneralPermissionEntry, String>)
				DGFileGeneralPermissionEntry::setUuid);
		attributeGetterFunctions.put(
			"externalReferenceCode",
			DGFileGeneralPermissionEntry::getExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<DGFileGeneralPermissionEntry, String>)
				DGFileGeneralPermissionEntry::setExternalReferenceCode);
		attributeGetterFunctions.put(
			"fileGeneralPermissionId",
			DGFileGeneralPermissionEntry::getFileGeneralPermissionId);
		attributeSetterBiConsumers.put(
			"fileGeneralPermissionId",
			(BiConsumer<DGFileGeneralPermissionEntry, Long>)
				DGFileGeneralPermissionEntry::setFileGeneralPermissionId);
		attributeGetterFunctions.put(
			"groupId", DGFileGeneralPermissionEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<DGFileGeneralPermissionEntry, Long>)
				DGFileGeneralPermissionEntry::setGroupId);
		attributeGetterFunctions.put(
			"companyId", DGFileGeneralPermissionEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DGFileGeneralPermissionEntry, Long>)
				DGFileGeneralPermissionEntry::setCompanyId);
		attributeGetterFunctions.put(
			"userId", DGFileGeneralPermissionEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<DGFileGeneralPermissionEntry, Long>)
				DGFileGeneralPermissionEntry::setUserId);
		attributeGetterFunctions.put(
			"userName", DGFileGeneralPermissionEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DGFileGeneralPermissionEntry, String>)
				DGFileGeneralPermissionEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", DGFileGeneralPermissionEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DGFileGeneralPermissionEntry, Date>)
				DGFileGeneralPermissionEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DGFileGeneralPermissionEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DGFileGeneralPermissionEntry, Date>)
				DGFileGeneralPermissionEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"customerId", DGFileGeneralPermissionEntry::getCustomerId);
		attributeSetterBiConsumers.put(
			"customerId",
			(BiConsumer<DGFileGeneralPermissionEntry, Long>)
				DGFileGeneralPermissionEntry::setCustomerId);
		attributeGetterFunctions.put(
			"creatorId", DGFileGeneralPermissionEntry::getCreatorId);
		attributeSetterBiConsumers.put(
			"creatorId",
			(BiConsumer<DGFileGeneralPermissionEntry, Long>)
				DGFileGeneralPermissionEntry::setCreatorId);
		attributeGetterFunctions.put(
			"fileId", DGFileGeneralPermissionEntry::getFileId);
		attributeSetterBiConsumers.put(
			"fileId",
			(BiConsumer<DGFileGeneralPermissionEntry, Long>)
				DGFileGeneralPermissionEntry::setFileId);
		attributeGetterFunctions.put(
			"allowed", DGFileGeneralPermissionEntry::getAllowed);
		attributeSetterBiConsumers.put(
			"allowed",
			(BiConsumer<DGFileGeneralPermissionEntry, String>)
				DGFileGeneralPermissionEntry::setAllowed);
		attributeGetterFunctions.put(
			"role", DGFileGeneralPermissionEntry::getRole);
		attributeSetterBiConsumers.put(
			"role",
			(BiConsumer<DGFileGeneralPermissionEntry, String>)
				DGFileGeneralPermissionEntry::setRole);
		attributeGetterFunctions.put(
			"type", DGFileGeneralPermissionEntry::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<DGFileGeneralPermissionEntry, String>)
				DGFileGeneralPermissionEntry::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@Override
	public long getFileGeneralPermissionId() {
		return _fileGeneralPermissionId;
	}

	@Override
	public void setFileGeneralPermissionId(long fileGeneralPermissionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileGeneralPermissionId = fileGeneralPermissionId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCustomerId() {
		return _customerId;
	}

	@Override
	public void setCustomerId(long customerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customerId = customerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCustomerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("customerId"));
	}

	@Override
	public long getCreatorId() {
		return _creatorId;
	}

	@Override
	public void setCreatorId(long creatorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creatorId = creatorId;
	}

	@Override
	public long getFileId() {
		return _fileId;
	}

	@Override
	public void setFileId(long fileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileId = fileId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFileId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("fileId"));
	}

	@Override
	public String getAllowed() {
		if (_allowed == null) {
			return "";
		}
		else {
			return _allowed;
		}
	}

	@Override
	public void setAllowed(String allowed) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_allowed = allowed;
	}

	@Override
	public String getRole() {
		if (_role == null) {
			return "";
		}
		else {
			return _role;
		}
	}

	@Override
	public void setRole(String role) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_role = role;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalType() {
		return getColumnOriginalValue("type_");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				DGFileGeneralPermissionEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DGFileGeneralPermissionEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DGFileGeneralPermissionEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DGFileGeneralPermissionEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DGFileGeneralPermissionEntryImpl dgFileGeneralPermissionEntryImpl =
			new DGFileGeneralPermissionEntryImpl();

		dgFileGeneralPermissionEntryImpl.setUuid(getUuid());
		dgFileGeneralPermissionEntryImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		dgFileGeneralPermissionEntryImpl.setFileGeneralPermissionId(
			getFileGeneralPermissionId());
		dgFileGeneralPermissionEntryImpl.setGroupId(getGroupId());
		dgFileGeneralPermissionEntryImpl.setCompanyId(getCompanyId());
		dgFileGeneralPermissionEntryImpl.setUserId(getUserId());
		dgFileGeneralPermissionEntryImpl.setUserName(getUserName());
		dgFileGeneralPermissionEntryImpl.setCreateDate(getCreateDate());
		dgFileGeneralPermissionEntryImpl.setModifiedDate(getModifiedDate());
		dgFileGeneralPermissionEntryImpl.setCustomerId(getCustomerId());
		dgFileGeneralPermissionEntryImpl.setCreatorId(getCreatorId());
		dgFileGeneralPermissionEntryImpl.setFileId(getFileId());
		dgFileGeneralPermissionEntryImpl.setAllowed(getAllowed());
		dgFileGeneralPermissionEntryImpl.setRole(getRole());
		dgFileGeneralPermissionEntryImpl.setType(getType());

		dgFileGeneralPermissionEntryImpl.resetOriginalValues();

		return dgFileGeneralPermissionEntryImpl;
	}

	@Override
	public DGFileGeneralPermissionEntry cloneWithOriginalValues() {
		DGFileGeneralPermissionEntryImpl dgFileGeneralPermissionEntryImpl =
			new DGFileGeneralPermissionEntryImpl();

		dgFileGeneralPermissionEntryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		dgFileGeneralPermissionEntryImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		dgFileGeneralPermissionEntryImpl.setFileGeneralPermissionId(
			this.<Long>getColumnOriginalValue("fileGeneralPermissionId"));
		dgFileGeneralPermissionEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		dgFileGeneralPermissionEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		dgFileGeneralPermissionEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		dgFileGeneralPermissionEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		dgFileGeneralPermissionEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		dgFileGeneralPermissionEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		dgFileGeneralPermissionEntryImpl.setCustomerId(
			this.<Long>getColumnOriginalValue("customerId"));
		dgFileGeneralPermissionEntryImpl.setCreatorId(
			this.<Long>getColumnOriginalValue("creatorId"));
		dgFileGeneralPermissionEntryImpl.setFileId(
			this.<Long>getColumnOriginalValue("fileId"));
		dgFileGeneralPermissionEntryImpl.setAllowed(
			this.<String>getColumnOriginalValue("allowed"));
		dgFileGeneralPermissionEntryImpl.setRole(
			this.<String>getColumnOriginalValue("role_"));
		dgFileGeneralPermissionEntryImpl.setType(
			this.<String>getColumnOriginalValue("type_"));

		return dgFileGeneralPermissionEntryImpl;
	}

	@Override
	public int compareTo(
		DGFileGeneralPermissionEntry dgFileGeneralPermissionEntry) {

		long primaryKey = dgFileGeneralPermissionEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DGFileGeneralPermissionEntry)) {
			return false;
		}

		DGFileGeneralPermissionEntry dgFileGeneralPermissionEntry =
			(DGFileGeneralPermissionEntry)object;

		long primaryKey = dgFileGeneralPermissionEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DGFileGeneralPermissionEntry> toCacheModel() {
		DGFileGeneralPermissionEntryCacheModel
			dgFileGeneralPermissionEntryCacheModel =
				new DGFileGeneralPermissionEntryCacheModel();

		dgFileGeneralPermissionEntryCacheModel.uuid = getUuid();

		String uuid = dgFileGeneralPermissionEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dgFileGeneralPermissionEntryCacheModel.uuid = null;
		}

		dgFileGeneralPermissionEntryCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			dgFileGeneralPermissionEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			dgFileGeneralPermissionEntryCacheModel.externalReferenceCode = null;
		}

		dgFileGeneralPermissionEntryCacheModel.fileGeneralPermissionId =
			getFileGeneralPermissionId();

		dgFileGeneralPermissionEntryCacheModel.groupId = getGroupId();

		dgFileGeneralPermissionEntryCacheModel.companyId = getCompanyId();

		dgFileGeneralPermissionEntryCacheModel.userId = getUserId();

		dgFileGeneralPermissionEntryCacheModel.userName = getUserName();

		String userName = dgFileGeneralPermissionEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dgFileGeneralPermissionEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dgFileGeneralPermissionEntryCacheModel.createDate =
				createDate.getTime();
		}
		else {
			dgFileGeneralPermissionEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dgFileGeneralPermissionEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			dgFileGeneralPermissionEntryCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		dgFileGeneralPermissionEntryCacheModel.customerId = getCustomerId();

		dgFileGeneralPermissionEntryCacheModel.creatorId = getCreatorId();

		dgFileGeneralPermissionEntryCacheModel.fileId = getFileId();

		dgFileGeneralPermissionEntryCacheModel.allowed = getAllowed();

		String allowed = dgFileGeneralPermissionEntryCacheModel.allowed;

		if ((allowed != null) && (allowed.length() == 0)) {
			dgFileGeneralPermissionEntryCacheModel.allowed = null;
		}

		dgFileGeneralPermissionEntryCacheModel.role = getRole();

		String role = dgFileGeneralPermissionEntryCacheModel.role;

		if ((role != null) && (role.length() == 0)) {
			dgFileGeneralPermissionEntryCacheModel.role = null;
		}

		dgFileGeneralPermissionEntryCacheModel.type = getType();

		String type = dgFileGeneralPermissionEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			dgFileGeneralPermissionEntryCacheModel.type = null;
		}

		return dgFileGeneralPermissionEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DGFileGeneralPermissionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DGFileGeneralPermissionEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DGFileGeneralPermissionEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DGFileGeneralPermissionEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DGFileGeneralPermissionEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DGFileGeneralPermissionEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DGFileGeneralPermissionEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(DGFileGeneralPermissionEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, DGFileGeneralPermissionEntry>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private String _uuid;
	private String _externalReferenceCode;
	private long _fileGeneralPermissionId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _customerId;
	private long _creatorId;
	private long _fileId;
	private String _allowed;
	private String _role;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DGFileGeneralPermissionEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DGFileGeneralPermissionEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put(
			"fileGeneralPermissionId", _fileGeneralPermissionId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("customerId", _customerId);
		_columnOriginalValues.put("creatorId", _creatorId);
		_columnOriginalValues.put("fileId", _fileId);
		_columnOriginalValues.put("allowed", _allowed);
		_columnOriginalValues.put("role_", _role);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("role_", "role");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("fileGeneralPermissionId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("customerId", 512L);

		columnBitmasks.put("creatorId", 1024L);

		columnBitmasks.put("fileId", 2048L);

		columnBitmasks.put("allowed", 4096L);

		columnBitmasks.put("role_", 8192L);

		columnBitmasks.put("type_", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DGFileGeneralPermissionEntry _escapedModel;

}