create table DG_AddressEntry (
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	addressId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	creatorId LONG,
	customerId LONG,
	detail VARCHAR(75) null,
	postalCode VARCHAR(75) null,
	ward VARCHAR(75) null,
	district VARCHAR(75) null,
	province VARCHAR(75) null,
	country VARCHAR(75) null,
	wardCode VARCHAR(75) null,
	districtCode VARCHAR(75) null,
	provinceCode VARCHAR(75) null,
	countryCode VARCHAR(75) null,
	title VARCHAR(75) null
);