components:
    schemas:
        Address:
            description: Present address of object
            properties:
                id:
                    description: The Address ID.
                    type: integer
                    format: int64
                    readOnly: true
                    example: 1
                externalReferenceCode:
                    readOnly: true
                    type: string
                detail:
                    description: The Address detail.
                    type: string
                    example: "so 159 ngach 5 to 5 duong Le Loi phuong Ha Tri quan Ha Dong thanh pho Ha Noi"
                postalCode:
                    description: The postal code detail.
                    type: string
                    example: "100000"
                ward:
                    description: The Address ward.
                    type: string
                    example: "phuong Ha Tri"
                wardCode:
                    description: The Address ward Code.
                    type: string
                    example: "HT"
                district:
                    description: The Address district.
                    type: string
                    example: "quan Ha Dong"
                districtCode:
                    description: The Address district Code.
                    type: string
                    example: "HD"
                province:
                    description: The Address province.
                    type: string
                    example: "thanh pho Ha Noi"
                provinceCode:
                    description: The Address province Code.
                    type: string
                    example: "HN"
                country:
                    description: The Address country.
                    type: string
                    example: "Viet Nam"
                countryCode:
                    description: The Address country Code.
                    type: string
                    example: "VN"
                title:
                    description: The title of address
                    type: string
                    example: "phuong Ha Tri quan Ha Dong thanh pho Ha Noi"
            type: object
info:
    description: "AddressesRestBuilder REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "AddressesRestBuilder"
    version: v2.0
openapi: 3.0.1
paths:
    "/addresses/{addressId}":
        get:
            operationId: getAddress
            summary: Get address by ID
            parameters:
                - in: path
                  name: addressId
                  description: Address ID
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Address"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Address"
                    description: "Get a address"
            tags: [ "Address" ]
        delete:
            operationId: deleteAddress
            summary: Delete address by ID
            parameters:
                - in: path
                  name: addressId
                  required: true
                  schema:
                      type: integer
                      format: int64
            responses:
                204:
                    content:
                        application/json: { }
                        application/xml: { }
                    description: ""
            tags: [ "Address" ]
        put:
            operationId: putAddress
            summary: Update address by ID
            parameters:
                - in: path
                  name: addressId
                  required: true
                  schema:
                      type: integer
                      format: int64
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Address"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Address"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Address"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Address"
                    description: ""
            tags: [ "Address" ]
    "/addresses":
        get:
            operationId: getAddresses
            summary: Get list address
            description: Retrieves the addresses. Results can be paginated, filtered, searched, and sorted.
            tags: [ "Address" ]
            parameters:
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    description: A paged array of addresses
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Address"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Address"
                                type: array
        post:
            operationId: addAddress
            summary: Add new Address

            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Address"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Address"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Address"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Address"
                    description: ""
            tags: [ "Address" ]
    "/addresses/by-external-reference-code/{externalReferenceCode}":
        put:
            tags: ["Address"]
            description: Update a Address by externalReferenceCode
            operationId: putAddressByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Address"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Address"
            responses:
                200:
                    description:
                        "Update a Address"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Address"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Address"
        get:
            tags: ["Address"]
            description: Get a Address by externalReferenceCode
            operationId: getAddressByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                200:
                    description:
                        "Get a Address"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Address"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Address"
        delete:
            tags: ["Address"]
            description: Delete a Address by externalReferenceCode
            operationId: deleteAddressByExternalReferenceCode
            parameters:
                - in: path
                  name: externalReferenceCode
                  required: true
                  schema:
                      type: string
            responses:
                204:
                    description:
                        "Delete a Address"
                    content:
                        application/json: {}
                        application/xml: {}