apiDir: "../address-rest-api/src/main/java"
apiPackagePath: "com.dogoo.address.rest"
application:
    baseURI: "/dogoo/address-rest"
    className: "AddressRestApplication"
    name: "AddressRest"
author: "datdt"
clientDir: "../address-rest-client/src/main/java"
testDir: "../address-rest-test/src/testIntegration/java"