/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.department.service.model.impl;

import com.dogoo.department.service.model.DepartmentEntry;
import com.dogoo.department.service.model.DepartmentEntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DepartmentEntry service. Represents a row in the &quot;DG_DepartmentEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DepartmentEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DepartmentEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DepartmentEntryImpl
 * @generated
 */
public class DepartmentEntryModelImpl
	extends BaseModelImpl<DepartmentEntry> implements DepartmentEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a department entry model instance should use the <code>DepartmentEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DG_DepartmentEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"departmentId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"creatorId", Types.BIGINT},
		{"customerId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"code_", Types.VARCHAR}, {"parentId", Types.BIGINT},
		{"order_", Types.INTEGER}, {"type_", Types.VARCHAR},
		{"businessId", Types.BIGINT}, {"tax", Types.VARCHAR},
		{"address", Types.VARCHAR}, {"headOffice", Types.VARCHAR},
		{"alias_", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("departmentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("creatorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("customerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("parentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("order_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("businessId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tax", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("headOffice", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("alias_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DG_DepartmentEntry (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,departmentId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,creatorId LONG,customerId LONG,name VARCHAR(75) null,code_ VARCHAR(75) null,parentId LONG,order_ INTEGER,type_ VARCHAR(75) null,businessId LONG,tax VARCHAR(75) null,address VARCHAR(75) null,headOffice VARCHAR(75) null,alias_ VARCHAR(75) null,description VARCHAR(75) null,status VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table DG_DepartmentEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY departmentEntry.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DG_DepartmentEntry.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BUSINESSID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CUSTOMERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TAX_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 512L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DepartmentEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _departmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDepartmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _departmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DepartmentEntry.class;
	}

	@Override
	public String getModelClassName() {
		return DepartmentEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DepartmentEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DepartmentEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DepartmentEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DepartmentEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DepartmentEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DepartmentEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DepartmentEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DepartmentEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DepartmentEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DepartmentEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DepartmentEntry.class.getClassLoader(), DepartmentEntry.class,
			ModelWrapper.class);

		try {
			Constructor<DepartmentEntry> constructor =
				(Constructor<DepartmentEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<DepartmentEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DepartmentEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DepartmentEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<DepartmentEntry, Object>>();
		Map<String, BiConsumer<DepartmentEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DepartmentEntry, ?>>();

		attributeGetterFunctions.put("uuid", DepartmentEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<DepartmentEntry, String>)DepartmentEntry::setUuid);
		attributeGetterFunctions.put(
			"externalReferenceCode", DepartmentEntry::getExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<DepartmentEntry, String>)
				DepartmentEntry::setExternalReferenceCode);
		attributeGetterFunctions.put(
			"departmentId", DepartmentEntry::getDepartmentId);
		attributeSetterBiConsumers.put(
			"departmentId",
			(BiConsumer<DepartmentEntry, Long>)
				DepartmentEntry::setDepartmentId);
		attributeGetterFunctions.put("groupId", DepartmentEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<DepartmentEntry, Long>)DepartmentEntry::setGroupId);
		attributeGetterFunctions.put(
			"companyId", DepartmentEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DepartmentEntry, Long>)DepartmentEntry::setCompanyId);
		attributeGetterFunctions.put("userId", DepartmentEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<DepartmentEntry, Long>)DepartmentEntry::setUserId);
		attributeGetterFunctions.put("userName", DepartmentEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DepartmentEntry, String>)DepartmentEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", DepartmentEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DepartmentEntry, Date>)DepartmentEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DepartmentEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DepartmentEntry, Date>)
				DepartmentEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"creatorId", DepartmentEntry::getCreatorId);
		attributeSetterBiConsumers.put(
			"creatorId",
			(BiConsumer<DepartmentEntry, Long>)DepartmentEntry::setCreatorId);
		attributeGetterFunctions.put(
			"customerId", DepartmentEntry::getCustomerId);
		attributeSetterBiConsumers.put(
			"customerId",
			(BiConsumer<DepartmentEntry, Long>)DepartmentEntry::setCustomerId);
		attributeGetterFunctions.put("name", DepartmentEntry::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<DepartmentEntry, String>)DepartmentEntry::setName);
		attributeGetterFunctions.put("code", DepartmentEntry::getCode);
		attributeSetterBiConsumers.put(
			"code",
			(BiConsumer<DepartmentEntry, String>)DepartmentEntry::setCode);
		attributeGetterFunctions.put("parentId", DepartmentEntry::getParentId);
		attributeSetterBiConsumers.put(
			"parentId",
			(BiConsumer<DepartmentEntry, Long>)DepartmentEntry::setParentId);
		attributeGetterFunctions.put("order", DepartmentEntry::getOrder);
		attributeSetterBiConsumers.put(
			"order",
			(BiConsumer<DepartmentEntry, Integer>)DepartmentEntry::setOrder);
		attributeGetterFunctions.put("type", DepartmentEntry::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<DepartmentEntry, String>)DepartmentEntry::setType);
		attributeGetterFunctions.put(
			"businessId", DepartmentEntry::getBusinessId);
		attributeSetterBiConsumers.put(
			"businessId",
			(BiConsumer<DepartmentEntry, Long>)DepartmentEntry::setBusinessId);
		attributeGetterFunctions.put("tax", DepartmentEntry::getTax);
		attributeSetterBiConsumers.put(
			"tax",
			(BiConsumer<DepartmentEntry, String>)DepartmentEntry::setTax);
		attributeGetterFunctions.put("address", DepartmentEntry::getAddress);
		attributeSetterBiConsumers.put(
			"address",
			(BiConsumer<DepartmentEntry, String>)DepartmentEntry::setAddress);
		attributeGetterFunctions.put(
			"headOffice", DepartmentEntry::getHeadOffice);
		attributeSetterBiConsumers.put(
			"headOffice",
			(BiConsumer<DepartmentEntry, String>)
				DepartmentEntry::setHeadOffice);
		attributeGetterFunctions.put("alias", DepartmentEntry::getAlias);
		attributeSetterBiConsumers.put(
			"alias",
			(BiConsumer<DepartmentEntry, String>)DepartmentEntry::setAlias);
		attributeGetterFunctions.put(
			"description", DepartmentEntry::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<DepartmentEntry, String>)
				DepartmentEntry::setDescription);
		attributeGetterFunctions.put("status", DepartmentEntry::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<DepartmentEntry, String>)DepartmentEntry::setStatus);
		attributeGetterFunctions.put(
			"statusDate", DepartmentEntry::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<DepartmentEntry, Date>)DepartmentEntry::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@Override
	public long getDepartmentId() {
		return _departmentId;
	}

	@Override
	public void setDepartmentId(long departmentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_departmentId = departmentId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCreatorId() {
		return _creatorId;
	}

	@Override
	public void setCreatorId(long creatorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creatorId = creatorId;
	}

	@Override
	public long getCustomerId() {
		return _customerId;
	}

	@Override
	public void setCustomerId(long customerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customerId = customerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCustomerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("customerId"));
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_code = code;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCode() {
		return getColumnOriginalValue("code_");
	}

	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentId = parentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentId"));
	}

	@Override
	public Integer getOrder() {
		return _order;
	}

	@Override
	public void setOrder(Integer order) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_order = order;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public long getBusinessId() {
		return _businessId;
	}

	@Override
	public void setBusinessId(long businessId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_businessId = businessId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalBusinessId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("businessId"));
	}

	@Override
	public String getTax() {
		if (_tax == null) {
			return "";
		}
		else {
			return _tax;
		}
	}

	@Override
	public void setTax(String tax) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tax = tax;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTax() {
		return getColumnOriginalValue("tax");
	}

	@Override
	public String getAddress() {
		if (_address == null) {
			return "";
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_address = address;
	}

	@Override
	public String getHeadOffice() {
		if (_headOffice == null) {
			return "";
		}
		else {
			return _headOffice;
		}
	}

	@Override
	public void setHeadOffice(String headOffice) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_headOffice = headOffice;
	}

	@Override
	public String getAlias() {
		if (_alias == null) {
			return "";
		}
		else {
			return _alias;
		}
	}

	@Override
	public void setAlias(String alias) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_alias = alias;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DepartmentEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DepartmentEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DepartmentEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DepartmentEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DepartmentEntryImpl departmentEntryImpl = new DepartmentEntryImpl();

		departmentEntryImpl.setUuid(getUuid());
		departmentEntryImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		departmentEntryImpl.setDepartmentId(getDepartmentId());
		departmentEntryImpl.setGroupId(getGroupId());
		departmentEntryImpl.setCompanyId(getCompanyId());
		departmentEntryImpl.setUserId(getUserId());
		departmentEntryImpl.setUserName(getUserName());
		departmentEntryImpl.setCreateDate(getCreateDate());
		departmentEntryImpl.setModifiedDate(getModifiedDate());
		departmentEntryImpl.setCreatorId(getCreatorId());
		departmentEntryImpl.setCustomerId(getCustomerId());
		departmentEntryImpl.setName(getName());
		departmentEntryImpl.setCode(getCode());
		departmentEntryImpl.setParentId(getParentId());
		departmentEntryImpl.setOrder(getOrder());
		departmentEntryImpl.setType(getType());
		departmentEntryImpl.setBusinessId(getBusinessId());
		departmentEntryImpl.setTax(getTax());
		departmentEntryImpl.setAddress(getAddress());
		departmentEntryImpl.setHeadOffice(getHeadOffice());
		departmentEntryImpl.setAlias(getAlias());
		departmentEntryImpl.setDescription(getDescription());
		departmentEntryImpl.setStatus(getStatus());
		departmentEntryImpl.setStatusDate(getStatusDate());

		departmentEntryImpl.resetOriginalValues();

		return departmentEntryImpl;
	}

	@Override
	public DepartmentEntry cloneWithOriginalValues() {
		DepartmentEntryImpl departmentEntryImpl = new DepartmentEntryImpl();

		departmentEntryImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		departmentEntryImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		departmentEntryImpl.setDepartmentId(
			this.<Long>getColumnOriginalValue("departmentId"));
		departmentEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		departmentEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		departmentEntryImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		departmentEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		departmentEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		departmentEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		departmentEntryImpl.setCreatorId(
			this.<Long>getColumnOriginalValue("creatorId"));
		departmentEntryImpl.setCustomerId(
			this.<Long>getColumnOriginalValue("customerId"));
		departmentEntryImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		departmentEntryImpl.setCode(
			this.<String>getColumnOriginalValue("code_"));
		departmentEntryImpl.setParentId(
			this.<Long>getColumnOriginalValue("parentId"));
		departmentEntryImpl.setOrder(
			this.<Integer>getColumnOriginalValue("order_"));
		departmentEntryImpl.setType(
			this.<String>getColumnOriginalValue("type_"));
		departmentEntryImpl.setBusinessId(
			this.<Long>getColumnOriginalValue("businessId"));
		departmentEntryImpl.setTax(this.<String>getColumnOriginalValue("tax"));
		departmentEntryImpl.setAddress(
			this.<String>getColumnOriginalValue("address"));
		departmentEntryImpl.setHeadOffice(
			this.<String>getColumnOriginalValue("headOffice"));
		departmentEntryImpl.setAlias(
			this.<String>getColumnOriginalValue("alias_"));
		departmentEntryImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		departmentEntryImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		departmentEntryImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return departmentEntryImpl;
	}

	@Override
	public int compareTo(DepartmentEntry departmentEntry) {
		int value = 0;

		value = getName().compareTo(departmentEntry.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DepartmentEntry)) {
			return false;
		}

		DepartmentEntry departmentEntry = (DepartmentEntry)object;

		long primaryKey = departmentEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DepartmentEntry> toCacheModel() {
		DepartmentEntryCacheModel departmentEntryCacheModel =
			new DepartmentEntryCacheModel();

		departmentEntryCacheModel.uuid = getUuid();

		String uuid = departmentEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			departmentEntryCacheModel.uuid = null;
		}

		departmentEntryCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			departmentEntryCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			departmentEntryCacheModel.externalReferenceCode = null;
		}

		departmentEntryCacheModel.departmentId = getDepartmentId();

		departmentEntryCacheModel.groupId = getGroupId();

		departmentEntryCacheModel.companyId = getCompanyId();

		departmentEntryCacheModel.userId = getUserId();

		departmentEntryCacheModel.userName = getUserName();

		String userName = departmentEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			departmentEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			departmentEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			departmentEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			departmentEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			departmentEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		departmentEntryCacheModel.creatorId = getCreatorId();

		departmentEntryCacheModel.customerId = getCustomerId();

		departmentEntryCacheModel.name = getName();

		String name = departmentEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			departmentEntryCacheModel.name = null;
		}

		departmentEntryCacheModel.code = getCode();

		String code = departmentEntryCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			departmentEntryCacheModel.code = null;
		}

		departmentEntryCacheModel.parentId = getParentId();

		Integer order = getOrder();

		if (order != null) {
			departmentEntryCacheModel.order = order;
		}

		departmentEntryCacheModel.type = getType();

		String type = departmentEntryCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			departmentEntryCacheModel.type = null;
		}

		departmentEntryCacheModel.businessId = getBusinessId();

		departmentEntryCacheModel.tax = getTax();

		String tax = departmentEntryCacheModel.tax;

		if ((tax != null) && (tax.length() == 0)) {
			departmentEntryCacheModel.tax = null;
		}

		departmentEntryCacheModel.address = getAddress();

		String address = departmentEntryCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			departmentEntryCacheModel.address = null;
		}

		departmentEntryCacheModel.headOffice = getHeadOffice();

		String headOffice = departmentEntryCacheModel.headOffice;

		if ((headOffice != null) && (headOffice.length() == 0)) {
			departmentEntryCacheModel.headOffice = null;
		}

		departmentEntryCacheModel.alias = getAlias();

		String alias = departmentEntryCacheModel.alias;

		if ((alias != null) && (alias.length() == 0)) {
			departmentEntryCacheModel.alias = null;
		}

		departmentEntryCacheModel.description = getDescription();

		String description = departmentEntryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			departmentEntryCacheModel.description = null;
		}

		departmentEntryCacheModel.status = getStatus();

		String status = departmentEntryCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			departmentEntryCacheModel.status = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			departmentEntryCacheModel.statusDate = statusDate.getTime();
		}
		else {
			departmentEntryCacheModel.statusDate = Long.MIN_VALUE;
		}

		return departmentEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DepartmentEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DepartmentEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DepartmentEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((DepartmentEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DepartmentEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DepartmentEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DepartmentEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DepartmentEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DepartmentEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _externalReferenceCode;
	private long _departmentId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _creatorId;
	private long _customerId;
	private String _name;
	private String _code;
	private long _parentId;
	private Integer _order;
	private String _type;
	private long _businessId;
	private String _tax;
	private String _address;
	private String _headOffice;
	private String _alias;
	private String _description;
	private String _status;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DepartmentEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DepartmentEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("departmentId", _departmentId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("creatorId", _creatorId);
		_columnOriginalValues.put("customerId", _customerId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("code_", _code);
		_columnOriginalValues.put("parentId", _parentId);
		_columnOriginalValues.put("order_", _order);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("businessId", _businessId);
		_columnOriginalValues.put("tax", _tax);
		_columnOriginalValues.put("address", _address);
		_columnOriginalValues.put("headOffice", _headOffice);
		_columnOriginalValues.put("alias_", _alias);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("code_", "code");
		attributeNames.put("order_", "order");
		attributeNames.put("type_", "type");
		attributeNames.put("alias_", "alias");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("externalReferenceCode", 2L);

		columnBitmasks.put("departmentId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("creatorId", 512L);

		columnBitmasks.put("customerId", 1024L);

		columnBitmasks.put("name", 2048L);

		columnBitmasks.put("code_", 4096L);

		columnBitmasks.put("parentId", 8192L);

		columnBitmasks.put("order_", 16384L);

		columnBitmasks.put("type_", 32768L);

		columnBitmasks.put("businessId", 65536L);

		columnBitmasks.put("tax", 131072L);

		columnBitmasks.put("address", 262144L);

		columnBitmasks.put("headOffice", 524288L);

		columnBitmasks.put("alias_", 1048576L);

		columnBitmasks.put("description", 2097152L);

		columnBitmasks.put("status", 4194304L);

		columnBitmasks.put("statusDate", 8388608L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DepartmentEntry _escapedModel;

}