/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.common.auditing.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AuditingEntry service. Represents a row in the &quot;DG_Auditing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.common.auditing.service.model.impl.AuditingEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.common.auditing.service.model.impl.AuditingEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditingEntry
 * @generated
 */
@ProviderType
public interface AuditingEntryModel
	extends BaseModel<AuditingEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a auditing entry model instance should use the {@link AuditingEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this auditing entry.
	 *
	 * @return the primary key of this auditing entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this auditing entry.
	 *
	 * @param primaryKey the primary key of this auditing entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this auditing entry.
	 *
	 * @return the uuid of this auditing entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this auditing entry.
	 *
	 * @param uuid the uuid of this auditing entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this auditing entry.
	 *
	 * @return the external reference code of this auditing entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this auditing entry.
	 *
	 * @param externalReferenceCode the external reference code of this auditing entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the auditing ID of this auditing entry.
	 *
	 * @return the auditing ID of this auditing entry
	 */
	public long getAuditingId();

	/**
	 * Sets the auditing ID of this auditing entry.
	 *
	 * @param auditingId the auditing ID of this auditing entry
	 */
	public void setAuditingId(long auditingId);

	/**
	 * Returns the group ID of this auditing entry.
	 *
	 * @return the group ID of this auditing entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this auditing entry.
	 *
	 * @param groupId the group ID of this auditing entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this auditing entry.
	 *
	 * @return the company ID of this auditing entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this auditing entry.
	 *
	 * @param companyId the company ID of this auditing entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this auditing entry.
	 *
	 * @return the user ID of this auditing entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this auditing entry.
	 *
	 * @param userId the user ID of this auditing entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this auditing entry.
	 *
	 * @return the user uuid of this auditing entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this auditing entry.
	 *
	 * @param userUuid the user uuid of this auditing entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this auditing entry.
	 *
	 * @return the user name of this auditing entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this auditing entry.
	 *
	 * @param userName the user name of this auditing entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this auditing entry.
	 *
	 * @return the create date of this auditing entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this auditing entry.
	 *
	 * @param createDate the create date of this auditing entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the customer ID of this auditing entry.
	 *
	 * @return the customer ID of this auditing entry
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this auditing entry.
	 *
	 * @param customerId the customer ID of this auditing entry
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the creator ID of this auditing entry.
	 *
	 * @return the creator ID of this auditing entry
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this auditing entry.
	 *
	 * @param creatorId the creator ID of this auditing entry
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the creator name of this auditing entry.
	 *
	 * @return the creator name of this auditing entry
	 */
	@AutoEscape
	public String getCreatorName();

	/**
	 * Sets the creator name of this auditing entry.
	 *
	 * @param creatorName the creator name of this auditing entry
	 */
	public void setCreatorName(String creatorName);

	/**
	 * Returns the name of this auditing entry.
	 *
	 * @return the name of this auditing entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this auditing entry.
	 *
	 * @param name the name of this auditing entry
	 */
	public void setName(String name);

	/**
	 * Returns the event type of this auditing entry.
	 *
	 * @return the event type of this auditing entry
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this auditing entry.
	 *
	 * @param eventType the event type of this auditing entry
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the message of this auditing entry.
	 *
	 * @return the message of this auditing entry
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this auditing entry.
	 *
	 * @param message the message of this auditing entry
	 */
	public void setMessage(String message);

	/**
	 * Returns the payload of this auditing entry.
	 *
	 * @return the payload of this auditing entry
	 */
	@AutoEscape
	public String getPayload();

	/**
	 * Sets the payload of this auditing entry.
	 *
	 * @param payload the payload of this auditing entry
	 */
	public void setPayload(String payload);

	/**
	 * Returns the class pk ID of this auditing entry.
	 *
	 * @return the class pk ID of this auditing entry
	 */
	public long getClassPkId();

	/**
	 * Sets the class pk ID of this auditing entry.
	 *
	 * @param classPkId the class pk ID of this auditing entry
	 */
	public void setClassPkId(long classPkId);

	/**
	 * Returns the class pk name of this auditing entry.
	 *
	 * @return the class pk name of this auditing entry
	 */
	@AutoEscape
	public String getClassPkName();

	/**
	 * Sets the class pk name of this auditing entry.
	 *
	 * @param classPkName the class pk name of this auditing entry
	 */
	public void setClassPkName(String classPkName);

	/**
	 * Returns the parent pk ID of this auditing entry.
	 *
	 * @return the parent pk ID of this auditing entry
	 */
	public Long getParentPkId();

	/**
	 * Sets the parent pk ID of this auditing entry.
	 *
	 * @param parentPkId the parent pk ID of this auditing entry
	 */
	public void setParentPkId(Long parentPkId);

	/**
	 * Returns the parent pk name of this auditing entry.
	 *
	 * @return the parent pk name of this auditing entry
	 */
	@AutoEscape
	public String getParentPkName();

	/**
	 * Sets the parent pk name of this auditing entry.
	 *
	 * @param parentPkName the parent pk name of this auditing entry
	 */
	public void setParentPkName(String parentPkName);

	@Override
	public AuditingEntry cloneWithOriginalValues();

}