/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.dataitems.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataItemEntry service. Represents a row in the &quot;DG_DATAITEMENTRY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.dataitems.service.model.impl.DataItemEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.dataitems.service.model.impl.DataItemEntryImpl</code>.
 * </p>
 *
 * @author nghiatt
 * @see DataItemEntry
 * @generated
 */
@ProviderType
public interface DataItemEntryModel
	extends BaseModel<DataItemEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data item entry model instance should use the {@link DataItemEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this data item entry.
	 *
	 * @return the primary key of this data item entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data item entry.
	 *
	 * @param primaryKey the primary key of this data item entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this data item entry.
	 *
	 * @return the uuid of this data item entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this data item entry.
	 *
	 * @param uuid the uuid of this data item entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this data item entry.
	 *
	 * @return the external reference code of this data item entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this data item entry.
	 *
	 * @param externalReferenceCode the external reference code of this data item entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the data item ID of this data item entry.
	 *
	 * @return the data item ID of this data item entry
	 */
	public long getDataItemId();

	/**
	 * Sets the data item ID of this data item entry.
	 *
	 * @param dataItemId the data item ID of this data item entry
	 */
	public void setDataItemId(long dataItemId);

	/**
	 * Returns the group ID of this data item entry.
	 *
	 * @return the group ID of this data item entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this data item entry.
	 *
	 * @param groupId the group ID of this data item entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this data item entry.
	 *
	 * @return the company ID of this data item entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this data item entry.
	 *
	 * @param companyId the company ID of this data item entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this data item entry.
	 *
	 * @return the user ID of this data item entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this data item entry.
	 *
	 * @param userId the user ID of this data item entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this data item entry.
	 *
	 * @return the user uuid of this data item entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this data item entry.
	 *
	 * @param userUuid the user uuid of this data item entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this data item entry.
	 *
	 * @return the user name of this data item entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this data item entry.
	 *
	 * @param userName the user name of this data item entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this data item entry.
	 *
	 * @return the create date of this data item entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this data item entry.
	 *
	 * @param createDate the create date of this data item entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this data item entry.
	 *
	 * @return the modified date of this data item entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this data item entry.
	 *
	 * @param modifiedDate the modified date of this data item entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the creator ID of this data item entry.
	 *
	 * @return the creator ID of this data item entry
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this data item entry.
	 *
	 * @param creatorId the creator ID of this data item entry
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the customer ID of this data item entry.
	 *
	 * @return the customer ID of this data item entry
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this data item entry.
	 *
	 * @param customerId the customer ID of this data item entry
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the name of this data item entry.
	 *
	 * @return the name of this data item entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this data item entry.
	 *
	 * @param name the name of this data item entry
	 */
	public void setName(String name);

	/**
	 * Returns the description of this data item entry.
	 *
	 * @return the description of this data item entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this data item entry.
	 *
	 * @param description the description of this data item entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the order_ of this data item entry.
	 *
	 * @return the order_ of this data item entry
	 */
	public long getOrder_();

	/**
	 * Sets the order_ of this data item entry.
	 *
	 * @param order_ the order_ of this data item entry
	 */
	public void setOrder_(long order_);

	/**
	 * Returns the type of this data item entry.
	 *
	 * @return the type of this data item entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this data item entry.
	 *
	 * @param type the type of this data item entry
	 */
	public void setType(String type);

	/**
	 * Returns the parent ID of this data item entry.
	 *
	 * @return the parent ID of this data item entry
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this data item entry.
	 *
	 * @param parentId the parent ID of this data item entry
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the is default value of this data item entry.
	 *
	 * @return the is default value of this data item entry
	 */
	public boolean getIsDefaultValue();

	/**
	 * Returns <code>true</code> if this data item entry is is default value.
	 *
	 * @return <code>true</code> if this data item entry is is default value; <code>false</code> otherwise
	 */
	public boolean isIsDefaultValue();

	/**
	 * Sets whether this data item entry is is default value.
	 *
	 * @param isDefaultValue the is default value of this data item entry
	 */
	public void setIsDefaultValue(boolean isDefaultValue);

	@Override
	public DataItemEntry cloneWithOriginalValues();

}