/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.contact.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ContactEntry service. Represents a row in the &quot;DG_ContactEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.contact.service.model.impl.ContactEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.contact.service.model.impl.ContactEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContactEntry
 * @generated
 */
@ProviderType
public interface ContactEntryModel
	extends BaseModel<ContactEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contact entry model instance should use the {@link ContactEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this contact entry.
	 *
	 * @return the primary key of this contact entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this contact entry.
	 *
	 * @param primaryKey the primary key of this contact entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this contact entry.
	 *
	 * @return the uuid of this contact entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this contact entry.
	 *
	 * @param uuid the uuid of this contact entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this contact entry.
	 *
	 * @return the external reference code of this contact entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this contact entry.
	 *
	 * @param externalReferenceCode the external reference code of this contact entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the contact ID of this contact entry.
	 *
	 * @return the contact ID of this contact entry
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this contact entry.
	 *
	 * @param contactId the contact ID of this contact entry
	 */
	public void setContactId(long contactId);

	/**
	 * Returns the group ID of this contact entry.
	 *
	 * @return the group ID of this contact entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this contact entry.
	 *
	 * @param groupId the group ID of this contact entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this contact entry.
	 *
	 * @return the company ID of this contact entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this contact entry.
	 *
	 * @param companyId the company ID of this contact entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this contact entry.
	 *
	 * @return the user ID of this contact entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this contact entry.
	 *
	 * @param userId the user ID of this contact entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this contact entry.
	 *
	 * @return the user uuid of this contact entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this contact entry.
	 *
	 * @param userUuid the user uuid of this contact entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this contact entry.
	 *
	 * @return the user name of this contact entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this contact entry.
	 *
	 * @param userName the user name of this contact entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this contact entry.
	 *
	 * @return the create date of this contact entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this contact entry.
	 *
	 * @param createDate the create date of this contact entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this contact entry.
	 *
	 * @return the modified date of this contact entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this contact entry.
	 *
	 * @param modifiedDate the modified date of this contact entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the creator ID of this contact entry.
	 *
	 * @return the creator ID of this contact entry
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this contact entry.
	 *
	 * @param creatorId the creator ID of this contact entry
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the customer ID of this contact entry.
	 *
	 * @return the customer ID of this contact entry
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this contact entry.
	 *
	 * @param customerId the customer ID of this contact entry
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the facebook of this contact entry.
	 *
	 * @return the facebook of this contact entry
	 */
	@AutoEscape
	public String getFacebook();

	/**
	 * Sets the facebook of this contact entry.
	 *
	 * @param facebook the facebook of this contact entry
	 */
	public void setFacebook(String facebook);

	/**
	 * Returns the twitter of this contact entry.
	 *
	 * @return the twitter of this contact entry
	 */
	@AutoEscape
	public String getTwitter();

	/**
	 * Sets the twitter of this contact entry.
	 *
	 * @param twitter the twitter of this contact entry
	 */
	public void setTwitter(String twitter);

	/**
	 * Returns the linkedin of this contact entry.
	 *
	 * @return the linkedin of this contact entry
	 */
	@AutoEscape
	public String getLinkedin();

	/**
	 * Sets the linkedin of this contact entry.
	 *
	 * @param linkedin the linkedin of this contact entry
	 */
	public void setLinkedin(String linkedin);

	@Override
	public ContactEntry cloneWithOriginalValues();

}