/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.contact.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PhoneEntry service. Represents a row in the &quot;DG_PhoneEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.contact.service.model.impl.PhoneEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.contact.service.model.impl.PhoneEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhoneEntry
 * @generated
 */
@ProviderType
public interface PhoneEntryModel
	extends BaseModel<PhoneEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phone entry model instance should use the {@link PhoneEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this phone entry.
	 *
	 * @return the primary key of this phone entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phone entry.
	 *
	 * @param primaryKey the primary key of this phone entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this phone entry.
	 *
	 * @return the uuid of this phone entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this phone entry.
	 *
	 * @param uuid the uuid of this phone entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this phone entry.
	 *
	 * @return the external reference code of this phone entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this phone entry.
	 *
	 * @param externalReferenceCode the external reference code of this phone entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the phone ID of this phone entry.
	 *
	 * @return the phone ID of this phone entry
	 */
	public long getPhoneId();

	/**
	 * Sets the phone ID of this phone entry.
	 *
	 * @param phoneId the phone ID of this phone entry
	 */
	public void setPhoneId(long phoneId);

	/**
	 * Returns the group ID of this phone entry.
	 *
	 * @return the group ID of this phone entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this phone entry.
	 *
	 * @param groupId the group ID of this phone entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this phone entry.
	 *
	 * @return the company ID of this phone entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this phone entry.
	 *
	 * @param companyId the company ID of this phone entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this phone entry.
	 *
	 * @return the user ID of this phone entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this phone entry.
	 *
	 * @param userId the user ID of this phone entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this phone entry.
	 *
	 * @return the user uuid of this phone entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this phone entry.
	 *
	 * @param userUuid the user uuid of this phone entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this phone entry.
	 *
	 * @return the user name of this phone entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this phone entry.
	 *
	 * @param userName the user name of this phone entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this phone entry.
	 *
	 * @return the create date of this phone entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this phone entry.
	 *
	 * @param createDate the create date of this phone entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this phone entry.
	 *
	 * @return the modified date of this phone entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this phone entry.
	 *
	 * @param modifiedDate the modified date of this phone entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the creator ID of this phone entry.
	 *
	 * @return the creator ID of this phone entry
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this phone entry.
	 *
	 * @param creatorId the creator ID of this phone entry
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the customer ID of this phone entry.
	 *
	 * @return the customer ID of this phone entry
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this phone entry.
	 *
	 * @param customerId the customer ID of this phone entry
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the contact ID of this phone entry.
	 *
	 * @return the contact ID of this phone entry
	 */
	public long getContactId();

	/**
	 * Sets the contact ID of this phone entry.
	 *
	 * @param contactId the contact ID of this phone entry
	 */
	public void setContactId(long contactId);

	/**
	 * Returns the number of this phone entry.
	 *
	 * @return the number of this phone entry
	 */
	@AutoEscape
	public String getNumber();

	/**
	 * Sets the number of this phone entry.
	 *
	 * @param number the number of this phone entry
	 */
	public void setNumber(String number);

	/**
	 * Returns the is defaulted of this phone entry.
	 *
	 * @return the is defaulted of this phone entry
	 */
	public boolean getIsDefaulted();

	/**
	 * Returns <code>true</code> if this phone entry is is defaulted.
	 *
	 * @return <code>true</code> if this phone entry is is defaulted; <code>false</code> otherwise
	 */
	public boolean isIsDefaulted();

	/**
	 * Sets whether this phone entry is is defaulted.
	 *
	 * @param isDefaulted the is defaulted of this phone entry
	 */
	public void setIsDefaulted(boolean isDefaulted);

	/**
	 * Returns the description of this phone entry.
	 *
	 * @return the description of this phone entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this phone entry.
	 *
	 * @param description the description of this phone entry
	 */
	public void setDescription(String description);

	@Override
	public PhoneEntry cloneWithOriginalValues();

}