/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.common.files.manager.service.service.base;

import com.dogoo.common.files.manager.service.model.DGDocumentManagerEntry;
import com.dogoo.common.files.manager.service.service.DGDocumentManagerEntryLocalService;
import com.dogoo.common.files.manager.service.service.DGDocumentManagerEntryLocalServiceUtil;
import com.dogoo.common.files.manager.service.service.persistence.DGDocumentManagerEntryPersistence;
import com.dogoo.common.files.manager.service.service.persistence.DGFileDepartmentPermissionEntryPersistence;
import com.dogoo.common.files.manager.service.service.persistence.DGFileGeneralPermissionEntryPersistence;
import com.dogoo.common.files.manager.service.service.persistence.DGFileManagerEntryPersistence;
import com.dogoo.common.files.manager.service.service.persistence.DGFileSettingPermissionEntryPersistence;
import com.dogoo.common.files.manager.service.service.persistence.DGFileUserPermissionEntryPersistence;
import com.dogoo.common.files.manager.service.service.persistence.DGFileVersionEntryPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the dg document manager entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dogoo.common.files.manager.service.service.impl.DGDocumentManagerEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dogoo.common.files.manager.service.service.impl.DGDocumentManagerEntryLocalServiceImpl
 * @generated
 */
public abstract class DGDocumentManagerEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DGDocumentManagerEntryLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DGDocumentManagerEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DGDocumentManagerEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the dg document manager entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DGDocumentManagerEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgDocumentManagerEntry the dg document manager entry
	 * @return the dg document manager entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DGDocumentManagerEntry addDGDocumentManagerEntry(
		DGDocumentManagerEntry dgDocumentManagerEntry) {

		dgDocumentManagerEntry.setNew(true);

		return dgDocumentManagerEntryPersistence.update(dgDocumentManagerEntry);
	}

	/**
	 * Creates a new dg document manager entry with the primary key. Does not add the dg document manager entry to the database.
	 *
	 * @param documentManagerId the primary key for the new dg document manager entry
	 * @return the new dg document manager entry
	 */
	@Override
	@Transactional(enabled = false)
	public DGDocumentManagerEntry createDGDocumentManagerEntry(
		long documentManagerId) {

		return dgDocumentManagerEntryPersistence.create(documentManagerId);
	}

	/**
	 * Deletes the dg document manager entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DGDocumentManagerEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param documentManagerId the primary key of the dg document manager entry
	 * @return the dg document manager entry that was removed
	 * @throws PortalException if a dg document manager entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DGDocumentManagerEntry deleteDGDocumentManagerEntry(
			long documentManagerId)
		throws PortalException {

		return dgDocumentManagerEntryPersistence.remove(documentManagerId);
	}

	/**
	 * Deletes the dg document manager entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DGDocumentManagerEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgDocumentManagerEntry the dg document manager entry
	 * @return the dg document manager entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DGDocumentManagerEntry deleteDGDocumentManagerEntry(
		DGDocumentManagerEntry dgDocumentManagerEntry) {

		return dgDocumentManagerEntryPersistence.remove(dgDocumentManagerEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return dgDocumentManagerEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DGDocumentManagerEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dgDocumentManagerEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.common.files.manager.service.model.impl.DGDocumentManagerEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return dgDocumentManagerEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.common.files.manager.service.model.impl.DGDocumentManagerEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return dgDocumentManagerEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dgDocumentManagerEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return dgDocumentManagerEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DGDocumentManagerEntry fetchDGDocumentManagerEntry(
		long documentManagerId) {

		return dgDocumentManagerEntryPersistence.fetchByPrimaryKey(
			documentManagerId);
	}

	/**
	 * Returns the dg document manager entry matching the UUID and group.
	 *
	 * @param uuid the dg document manager entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching dg document manager entry, or <code>null</code> if a matching dg document manager entry could not be found
	 */
	@Override
	public DGDocumentManagerEntry fetchDGDocumentManagerEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return dgDocumentManagerEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the dg document manager entry with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the dg document manager entry's external reference code
	 * @return the matching dg document manager entry, or <code>null</code> if a matching dg document manager entry could not be found
	 */
	@Override
	public DGDocumentManagerEntry
		fetchDGDocumentManagerEntryByExternalReferenceCode(
			long companyId, String externalReferenceCode) {

		return dgDocumentManagerEntryPersistence.fetchByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * @deprecated As of Cavanaugh (7.4.x), replaced by {@link #fetchDGDocumentManagerEntryByExternalReferenceCode(long, String)}
	 */
	@Deprecated
	@Override
	public DGDocumentManagerEntry fetchDGDocumentManagerEntryByReferenceCode(
		long companyId, String externalReferenceCode) {

		return fetchDGDocumentManagerEntryByExternalReferenceCode(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the dg document manager entry with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the dg document manager entry's external reference code
	 * @return the matching dg document manager entry
	 * @throws PortalException if a matching dg document manager entry could not be found
	 */
	@Override
	public DGDocumentManagerEntry
			getDGDocumentManagerEntryByExternalReferenceCode(
				long companyId, String externalReferenceCode)
		throws PortalException {

		return dgDocumentManagerEntryPersistence.findByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the dg document manager entry with the primary key.
	 *
	 * @param documentManagerId the primary key of the dg document manager entry
	 * @return the dg document manager entry
	 * @throws PortalException if a dg document manager entry with the primary key could not be found
	 */
	@Override
	public DGDocumentManagerEntry getDGDocumentManagerEntry(
			long documentManagerId)
		throws PortalException {

		return dgDocumentManagerEntryPersistence.findByPrimaryKey(
			documentManagerId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			dgDocumentManagerEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DGDocumentManagerEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("documentManagerId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			dgDocumentManagerEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			DGDocumentManagerEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"documentManagerId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			dgDocumentManagerEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DGDocumentManagerEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("documentManagerId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<DGDocumentManagerEntry>() {

				@Override
				public void performAction(
						DGDocumentManagerEntry dgDocumentManagerEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, dgDocumentManagerEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					DGDocumentManagerEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dgDocumentManagerEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return dgDocumentManagerEntryLocalService.deleteDGDocumentManagerEntry(
			(DGDocumentManagerEntry)persistedModel);
	}

	@Override
	public BasePersistence<DGDocumentManagerEntry> getBasePersistence() {
		return dgDocumentManagerEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dgDocumentManagerEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the dg document manager entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the dg document manager entries
	 * @param companyId the primary key of the company
	 * @return the matching dg document manager entries, or an empty list if no matches were found
	 */
	@Override
	public List<DGDocumentManagerEntry>
		getDGDocumentManagerEntriesByUuidAndCompanyId(
			String uuid, long companyId) {

		return dgDocumentManagerEntryPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of dg document manager entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the dg document manager entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of dg document manager entries
	 * @param end the upper bound of the range of dg document manager entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching dg document manager entries, or an empty list if no matches were found
	 */
	@Override
	public List<DGDocumentManagerEntry>
		getDGDocumentManagerEntriesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<DGDocumentManagerEntry> orderByComparator) {

		return dgDocumentManagerEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the dg document manager entry matching the UUID and group.
	 *
	 * @param uuid the dg document manager entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching dg document manager entry
	 * @throws PortalException if a matching dg document manager entry could not be found
	 */
	@Override
	public DGDocumentManagerEntry getDGDocumentManagerEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return dgDocumentManagerEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the dg document manager entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.common.files.manager.service.model.impl.DGDocumentManagerEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of dg document manager entries
	 * @param end the upper bound of the range of dg document manager entries (not inclusive)
	 * @return the range of dg document manager entries
	 */
	@Override
	public List<DGDocumentManagerEntry> getDGDocumentManagerEntries(
		int start, int end) {

		return dgDocumentManagerEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dg document manager entries.
	 *
	 * @return the number of dg document manager entries
	 */
	@Override
	public int getDGDocumentManagerEntriesCount() {
		return dgDocumentManagerEntryPersistence.countAll();
	}

	/**
	 * Updates the dg document manager entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DGDocumentManagerEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dgDocumentManagerEntry the dg document manager entry
	 * @return the dg document manager entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DGDocumentManagerEntry updateDGDocumentManagerEntry(
		DGDocumentManagerEntry dgDocumentManagerEntry) {

		return dgDocumentManagerEntryPersistence.update(dgDocumentManagerEntry);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DGDocumentManagerEntryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		dgDocumentManagerEntryLocalService =
			(DGDocumentManagerEntryLocalService)aopProxy;

		_setLocalServiceUtilService(dgDocumentManagerEntryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DGDocumentManagerEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DGDocumentManagerEntry.class;
	}

	protected String getModelClassName() {
		return DGDocumentManagerEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				dgDocumentManagerEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DGDocumentManagerEntryLocalService dgDocumentManagerEntryLocalService) {

		try {
			Field field =
				DGDocumentManagerEntryLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, dgDocumentManagerEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected DGDocumentManagerEntryLocalService
		dgDocumentManagerEntryLocalService;

	@Reference
	protected DGDocumentManagerEntryPersistence
		dgDocumentManagerEntryPersistence;

	@Reference
	protected DGFileDepartmentPermissionEntryPersistence
		dgFileDepartmentPermissionEntryPersistence;

	@Reference
	protected DGFileGeneralPermissionEntryPersistence
		dgFileGeneralPermissionEntryPersistence;

	@Reference
	protected DGFileManagerEntryPersistence dgFileManagerEntryPersistence;

	@Reference
	protected DGFileSettingPermissionEntryPersistence
		dgFileSettingPermissionEntryPersistence;

	@Reference
	protected DGFileUserPermissionEntryPersistence
		dgFileUserPermissionEntryPersistence;

	@Reference
	protected DGFileVersionEntryPersistence dgFileVersionEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}