components:
  schemas:
    Auditing:
      description: Auditing Model
      properties:
        id:
          format: int64
          readOnly: true
          type: integer
        externalReferenceCode:
          readOnly: true
          type: string
        name:
          type: string
          readOnly: true
        eventType:
          type: string
          readOnly: true
        message:
          type: string
          readOnly: true
        payload:
          type: string
          readOnly: true
        date:
          type: string
          format: date-time
          readOnly: true
        creator:
          type: string
          readOnly: true
info:
  description: "AuditingRest REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "AuditingRest"
  version: v2.0
openapi: 3.0.1

paths:
  /auditings:
    get:
      tags:
        - Auditing
      description: Get List Auditing
      operationId: getAuditings
      parameters:
        - in: query
          name: classPkId
          schema:
            type: integer
            format: int64
        - in: query
          name: classPkName
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: startDate
          schema:
            type: string
            format: date-time
        - in: query
          name: endDate
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Get List Auditing
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Auditing'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Auditing'